version: "2"
services:
    #proxy:
    #  image: traefik:roquefort-alpine
    #  ports:
    #    - 80:80
        #- 8080:8080
    #  volumes:
    #    - ./proxy/traefik.toml:/etc/traefik/traefik.toml
    #    - /var/run/docker.sock:/var/run/docker.sock

    db:
      image: postgres:alpine
      environment:
          POSTGRES_USER: company_service
          POSTGRES_PASSWORD: pass
      ports:
        - 5432:5432

    api:
      build: api
      ports:
        - 4567:4567
      environment:
        - "DB_ADAPTER=postgresql"
        - "DB_HOST=db"
        - "DB_USER=company_service"
        - "DB_PASS=pass"
        - "DB_DB_NAME=company_service"
      volumes:
        - ./api/:/usr/src/app

    ui:
      build: ui
      ports:
        - 80:80
      environment:
        - "API_ENDPOINT=api:4567"
        - "NODE_ENV=production"
      volumes:
        - ./ui/:/usr/src/app:ro
