version: "2"
services:
    db:
      image: postgres:alpine
      environment:
          POSTGRES_USER: company_service
          POSTGRES_PASSWORD: pass
      ports:
        - 5432:5432

    api:
      build: api
      ports:
        - 4567:4567
      environment:
        - "DB_ADAPTER=postgresql"
        - "DB_HOST=db"
        - "DB_USER=company_service"
        - "DB_PASS=pass"
        - "DB_DB_NAME=company_service"
      volumes:
        - ./api/:/usr/src/app
